

modLoader="javafml" #mandatory

loaderVersion="[30,)" #mandatory (28 is current forge version)

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="stateq4444mod" #mandatory

version="1.0" #mandatory

displayName="Stateq4444 Mod" #mandatory

updateJSONURL="" #optional

displayURL="" #optional

logoFile="" #optional

credits="Thanks for this example mod goes to Java" #optional

authors="Love, Cheese and small house plants" #optional

description='''
DESCRIPTION!!!!!!!!

'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.stateq4444mod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.stateq4444mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"
